### ISSUE TITLE
File pointer isn't valid

### ISSUE THREAD

**Issue by Tyil** [PostCocoon/P6-TagLibC#1]
I'm using TagLibC in my [MusicLinker](https://github.com/tyil/musiclinker) project, but I'm getting the following `File pointer isn't valid` error rather often. To be precise, it happens 17624 out of 27419 times.

If needed, I can make MusicLinker output a list of file paths that are failing.

```
File pointer isn't vaild                                                                               
  in method validate at /home/tyil/.perl6/sources/5BD25E88C81D10D06A7E68655A12DEC530474105 (TagLibC::Wrapper) line 103                                                                                        
  in method track at /home/tyil/.perl6/sources/5BD25E88C81D10D06A7E68655A12DEC530474105 (TagLibC::Wrapper) line 185                                                                                           
  in sub make-link-path at bin/musiclinker.pl6 line 98                                                 
  in sub link-file at bin/musiclinker.pl6 line 25                                                      
  in block  at bin/musiclinker.pl6 line 137                                                            
  in sub MAIN at bin/musiclinker.pl6 line 136                                                          
  in block <unit> at bin/musiclinker.pl6 line 127                                                      
```

**Comment by the-eater** [comment]
I have found a case in my own music library that consistently dies on this investigating...

**Comment by the-eater** [comment]
So after running it over my lib I've concluded the following it throws this error when:

The filename has an invalid UTF-8 byte sequence thingy. e.g: `/remote/music/Unexistence/08-UneXist & OGM909 feat. Kerosene - Questa <U+10FFFD>xE8 Hardcore.wav`

Or there is no metadata available in the file, if your case doesn't involve those 2 points please provide more datas, thank you :)

**Comment by the-eater** [comment]
@Tyil bump?

**Comment by Tyil** [comment]
I am no longer working on that project, which makes it hard to debug at this point for me. I guess it's alright to close, if I ever use it again in a new project I can reopen if it happens again.
